# 第二題：
## 有A,B,C三個班級，每班皆有10個學生，期中考結束後，老師希望計算各班級每位學生的加權平均成績。
 
## 請隨機產生3個班級的成績單,每班10人,共五科,權重為weights=[0.25,0.25,0.25,0.15,0.10]。
## 請算出班級加權平均成績，並以一個array輸出。

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [10]:
# 亂數製造三個班級每班十人共五科的成績
# 分數設定為 0 至 100 的整數
grades = np.random.randint(0,101,size=[3, 10, 5])

In [11]:
grades

array([[[ 35,  25,  36,  12,  17],
        [ 17,  41,  77,   5,  35],
        [ 21,  36,  25,   1,  37],
        [  0,  74,  33,  72,  28],
        [ 64,  62,  21,  19,  72],
        [  0,  43,  59,  71,  13],
        [ 52,  26,  71,   9,  57],
        [ 73,   6,  75,   0,  21],
        [  7,  40,  48,  25,  37],
        [ 15,  80,  89,  31,  64]],

       [[ 17,  15,   3,  40,  46],
        [ 67,  68,  48,  77,  17],
        [ 13,  92,  83,  48,   1],
        [ 31,  81,  63,  33,  47],
        [ 52,  58,  10,  67,  99],
        [ 73,  56,  47, 100,  62],
        [ 92, 100,  86,  59,   1],
        [ 63,  97, 100,  87,  40],
        [ 17,  53,  45,  94,  55],
        [ 54,  46,  52,  79,  70]],

       [[ 50,  86,  85,  42,  80],
        [  4,  86,  50,  80,  52],
        [ 16,  63,  24,  10,  91],
        [ 62,  64,   9,  25,  39],
        [ 91,  18,  59,  95,  23],
        [ 73,   5,  16,  81,  92],
        [ 28,  64,  24,  89,  12],
        [ 85,  86,  11,  87,  96],
        [ 43,  7

In [12]:
#權重
weights = np.array([0.25,0.25,0.25,0.15,0.10])

In [14]:
# 計算每個人的個人加權平均成績
ind_grades = np.dot(grades, weights)

In [15]:
ind_grades

array([[ 27.5 ,  38.  ,  24.35,  40.35,  46.8 ,  37.45,  44.3 ,  40.6 ,
         31.2 ,  57.05],
       [ 19.35,  59.  ,  54.3 ,  53.4 ,  49.95,  65.2 ,  78.45,  82.05,
         48.35,  56.85],
       [ 69.55,  52.2 ,  36.35,  41.4 ,  58.55,  44.85,  43.55,  68.15,
         66.45,  65.75]])

In [16]:
# 計算班級平均
#axis =0 為班級，axis =1 為個人總分，此處用 mean 求班級平均
class_grades = np.mean(ind_grades, axis=1)

In [17]:
class_grades

array([ 38.76,  56.69,  54.68])